{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.runtime.enabled .Values.runtime.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "agi.runtime.fullname" . }}
  labels:
    {{- include "agi.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "agi.runtime.fullname" . }}
  minReplicas: {{ .Values.runtime.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.runtime.autoscaling.maxReplicas }}
  metrics:
    {{- with .Values.runtime.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with .Values.runtime.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
{{- end }}
