{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "agi.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "imagePullSecret.dockerconfigjson must be set when imagePullSecret.create=true" .Values.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
