// SPDX-License-Identifier: Apache-2.0
'use client';

import { Icon, ScreenHead } from '../components/m3';
import { ToolsTable } from '../components/tools-table';
import { DATA } from '../mock/data';

export default function ToolsScreen() {
  return (
    <div className="stack">
      <ScreenHead
        title="Tool catalogue"
        lede="Tools generated by agi-mcpfyer from registered OpenAPI specs. Use the test-invoke panel on detail pages to dry-run write tools safely."
        meta={`${DATA.tools.length} tools · ${new Set(DATA.tools.map((t) => t.domain)).size} domains · bundle v2026-05-21`}
        right={
          <>
            <a className="btn text" href="#">
              <Icon name="book" size={13} /> Catalogue spec
            </a>
            <button type="button" className="btn">
              <Icon name="download" /> Export
            </button>
          </>
        }
      />
      <ToolsTable tools={DATA.tools} />
    </div>
  );
}
