// SPDX-License-Identifier: Apache-2.0
/**
 * Tool catalogue route — server component.
 *
 * Fetches GET /tools from agi-runtime and unwraps the {pack, tools} envelope
 * (FR-TOOL-01, ADMIN_CONSOLE §3.3). Earlier the FE assumed the response was
 * a bare array and rendered nothing on real runtimes; the BE shape lands in
 * Wave 4b-C. We tolerate both shapes here (envelope OR bare array) so the
 * page is robust during the rollout, and degrade to an empty list on any
 * runtime error so the chrome still renders.
 *
 * Note: the BE endpoint shape is owned by 4b-C — we only consume it.
 */

import { Icon, ScreenHead } from '../components/m3';
import type { ToolSummary } from '@/lib/api/types';
import { runtimeFetch, RuntimeError } from '../components/runtime-fetch';
import { ToolCatalogue } from './tool-catalogue';

interface ToolsEnvelope {
  pack?: string;
  tools: ToolSummary[];
}

/**
 * Unwrap the /tools response. Handles three shapes safely:
 *   1. `{ pack, tools: [...] }` — the post-4b-C BE envelope (target).
 *   2. `[...]` — the legacy bare-array shape (in case the BE rollout lags).
 *   3. anything else — empty list.
 */
function unwrapTools(payload: unknown): ToolSummary[] {
  if (Array.isArray(payload)) {
    return payload as ToolSummary[];
  }
  if (payload && typeof payload === 'object' && 'tools' in payload) {
    const t = (payload as ToolsEnvelope).tools;
    return Array.isArray(t) ? t : [];
  }
  return [];
}

async function loadTools(): Promise<ToolSummary[]> {
  try {
    const raw = await runtimeFetch<unknown>('/tools', { cache: 'no-store' });
    return unwrapTools(raw);
  } catch (err) {
    // Fail-soft: render the empty state with chrome intact rather than 500
    // the whole route. The error chip on /health surfaces upstream issues.
    if (err instanceof RuntimeError) {
      // eslint-disable-next-line no-console
      console.warn('[tools] runtime fetch failed:', err.status, err.problem.title);
    }
    return [];
  }
}

export default async function ToolsScreen() {
  const tools = await loadTools();
  const domainCount = new Set(tools.map((t) => t.domain)).size;
  const bundleVersion =
    tools.find((t) => t.bundle_version)?.bundle_version ?? 'unknown';

  return (
    <div className="stack">
      <ScreenHead
        title="Tool catalogue"
        lede="Tools generated by agi-mcpfyer from registered OpenAPI specs. Use the test-invoke panel on detail pages to dry-run write tools safely."
        meta={`${tools.length} tools · ${domainCount} domains · bundle ${bundleVersion}`}
        right={
          <>
            <a className="btn text" href="#">
              <Icon name="book" size={13} /> Catalogue spec
            </a>
            <button type="button" className="btn">
              <Icon name="download" /> Export
            </button>
          </>
        }
      />
      <ToolCatalogue tools={tools} />
    </div>
  );
}
